on: [push]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Code-Coverage:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Initialization
      run: npm run initialize
    - name: Run tests
      run: mkdir tmp && npm run test-ci
    - name: Add comment on test result
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments \
        --data-binary "@tmp/report.json"
    - name: Finalize check
      run: exit ${{ env.CODE_COVERAGE_FAILURE_STATUS }}